version: "3.8"

services:
  compose-post-service:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
    command: ["ComposePostService"]
    hostname: compose-post-service
    image: yg397/social-network-microservices:latest
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  home-timeline-redis:
    hostname: home-timeline-redis
    image: redis
    command: "redis-server /social-network-microservices/config/redis.conf"
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  home-timeline-service:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
    command: ["HomeTimelineService"]
    hostname: home-timeline-service
    image: yg397/social-network-microservices:latest
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  media-frontend:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
    hostname: media-frontend
    image: yg397/media-frontend:xenial
    ports:
      - 8081:8080
    volumes:
      - ./media-frontend/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./media-frontend/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf

  media-memcached:
    hostname: media-memcached
    image: memcached
    command:
      - "-m 16384"
      - "-t 8"
      - "-I 32m"
      - "-c 4096"

  media-mongodb:
    hostname: media-mongodb
    image: mongo
    command: "mongod --nojournal --quiet --config /social-network-microservices/config/mongod.conf"
    # command: "mongod --serviceExecutor adaptive --listenBacklog 1024 --syncdelay 3600 --wiredTigerCacheSizeGB 2"
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  media-service:
    depends_on:
      - media-mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
    command: ["MediaService"]
    hostname: media-service
    image: yg397/social-network-microservices:latest
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  nginx-web-server:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "4"
          memory: 4G
    hostname: nginx-web-server
    image: yg397/openresty-thrift:xenial
    ports:
      - 8080:8080
    volumes:
      - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx-web-server/pages:/usr/local/openresty/nginx/pages
      - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./gen-lua:/gen-lua
      - ./docker/openresty-thrift/lua-thrift:/usr/local/openresty/lualib/thrift
      - ./keys:/keys

  post-storage-memcached:
    hostname: post-storage-memcached
    image: memcached
    command:
      - "-m 16384"
      - "-t 8"
      - "-I 32m"
      - "-c 4096"

  post-storage-mongodb:
    hostname: post-storage-mongodb
    image: mongo
    command: "mongod --nojournal --quiet --config /social-network-microservices/config/mongod.conf"
    # command: "mongod --serviceExecutor adaptive --listenBacklog 1024 --syncdelay 3600 --wiredTigerCacheSizeGB 75"
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  post-storage-service:
    depends_on:
      - post-storage-mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
    command: ["PostStorageService"]
    hostname: post-storage-service
    image: yg397/social-network-microservices:latest
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  social-graph-mongodb:
    hostname: social-graph-mongodb
    image: mongo
    command: "mongod --nojournal --quiet --config /social-network-microservices/config/mongod.conf"
    # command: "mongod --serviceExecutor adaptive --listenBacklog 1024 --syncdelay 3600 --wiredTigerCacheSizeGB 16"
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  social-graph-redis:
    hostname: social-graph-redis
    image: redis
    command: "redis-server /social-network-microservices/config/redis.conf"
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  social-graph-service:
    depends_on:
      - social-graph-mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
    command: ["SocialGraphService"]
    hostname: social-graph-service
    image: yg397/social-network-microservices:latest
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  text-service:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
    command: ["TextService"]
    hostname: text-service
    image: yg397/social-network-microservices:latest
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  unique-id-service:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
    command: ["UniqueIdService"]
    hostname: unique-id-service
    image: yg397/social-network-microservices:latest
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  url-shorten-memcached:
    hostname: url-shorten-memcached
    image: memcached
    command:
      - "-m 16384"
      - "-t 8"
      - "-I 32m"
      - "-c 4096"

  url-shorten-mongodb:
    hostname: url-shorten-mongodb
    image: mongo
    command: "mongod --nojournal --quiet --config /social-network-microservices/config/mongod.conf"
    # command: "mongod --serviceExecutor adaptive --listenBacklog 1024 --syncdelay 3600 --wiredTigerCacheSizeGB 36"
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  url-shorten-service:
    depends_on:
      - url-shorten-mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
    command: ["UrlShortenService"]
    hostname: url-shorten-service
    image: yg397/social-network-microservices:latest
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  user-memcached:
    hostname: user-memcached
    image: memcached
    command:
      - "-m 16384"
      - "-t 8"
      - "-I 32m"
      - "-c 4096"

  user-mention-service:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
    command: ["UserMentionService"]
    hostname: user-mention-service
    image: yg397/social-network-microservices:latest
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  user-mongodb:
    hostname: user-mongodb
    image: mongo
    command: "mongod --nojournal --quiet --config /social-network-microservices/config/mongod.conf"
    # command: "mongod --serviceExecutor adaptive --listenBacklog 1024 --syncdelay 3600 --wiredTigerCacheSizeGB 8"
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  user-service:
    depends_on:
      - user-mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
    command: ["UserService"]
    hostname: user-service
    image: yg397/social-network-microservices:latest
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  user-timeline-mongodb:
    hostname: user-timeline-mongodb
    image: mongo
    command: "mongod --nojournal --quiet --config /social-network-microservices/config/mongod.conf"
    # command: "mongod --serviceExecutor adaptive --listenBacklog 1024 --syncdelay 3600 --wiredTigerCacheSizeGB 75"
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  user-timeline-redis:
    hostname: user-timeline-redis
    image: redis
    command: "redis-server /social-network-microservices/config/redis.conf"
    volumes:
      - ./config:/social-network-microservices/config
      - ./keys:/keys

  user-timeline-service:
    depends_on:
      - user-timeline-mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1"
          memory: 1G
    command: ["UserTimelineService"]
    hostname: user-timeline-service
    image: yg397/social-network-microservices:latest
    volumes:
      - ./config:/social-network-microservices/config

  
networks:
  default:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.11.0.0/16
